version: "3.9"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: flask-app

    ports: 
     - "5000:5000"


    environment:
      APP_NAME: "Devops F:Lask CI/CD Pipeline"
      APP_VERSION: "1.0.0"
      APP_ENV: "Development"

      restart: unless-stopped